fst:
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.0.att LT.4.2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.1.att LT.4.2.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.2.att LT.4.2.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.3.att LT.4.2.3.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.4.att LT.4.2.4.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.5.att LT.4.2.5.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.6.att LT.4.2.6.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LT.4.2.7.att LT.4.2.7.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LTT.4.2.3.0.att LTT.4.2.3.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LTT.4.2.3.1.att LTT.4.2.3.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LTT.4.2.6.0.att LTT.4.2.6.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt LTT.4.2.6.1.att LTT.4.2.6.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.0.att PT.4.2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.1.att PT.4.2.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.2.att PT.4.2.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.3.att PT.4.2.3.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.4.att PT.4.2.4.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.5.att PT.4.2.5.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.6.att PT.4.2.6.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt PT.4.2.7.att PT.4.2.7.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt R.1.m2.0.att R.1.m2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt R.1.m3.0.att R.1.m3.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt R.1.m7.0.att R.1.m7.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt R.2.m2.0.att R.2.m2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt R.2.m3.0.att R.2.m3.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt R.2.m7.0.att R.2.m7.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SF.0.att SF.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SF.1.att SF.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SF.2.att SF.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SF.3.att SF.3.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SF.4.att SF.4.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SL.4.2.0.att SL.4.2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SL.4.2.1.att SL.4.2.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SL.4.2.2.att SL.4.2.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SL.4.2.3.att SL.4.2.3.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SP.4.2.0.att SP.4.2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SP.4.2.1.att SP.4.2.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SP.4.2.2.att SP.4.2.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt SP.4.2.3.att SP.4.2.3.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSL.4.2.0.att cSL.4.2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSL.4.2.1.att cSL.4.2.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSL.4.2.2.att cSL.4.2.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSL.4.2.3.att cSL.4.2.3.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSP.4.2.0.att cSP.4.2.0.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSP.4.2.1.att cSP.4.2.1.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSP.4.2.2.att cSP.4.2.2.fst
	fstcompile --isymbols=ins.txt --osymbols=outs.txt cSP.4.2.3.att cSP.4.2.3.fst
	mv *.fst lib_fst
clean_att: 
	rm *.att
clean_fst: 
	rm *.fst
